// CaseClicker social / multiplayer layer.
// @ts-nocheck
(function(){ "use strict";
var SUPABASE_URL="https://dkwmkvruzebnqlmvwzhy.supabase.co",SUPABASE_KEY="sb_publishable_Tur9X4MaQjH__4DnEtwAAQ_Xy9xVl5P",client=null,user=null,party=null,members=[],selectedItems=new Map(),channel=null,presenceChannel=null;
function el(id){return document.getElementById(id)} function money(v){return "$"+Number(v||0).toFixed(2)}
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]})}
function status(m,e){var n=el("ccSocialStatus");if(n){n.textContent=m;n.classList.toggle("error",!!e)}}
function username(){var i=el("username");if(i&&i.value.trim())return i.value.trim().slice(0,32);return(user&&user.user_metadata&&(user.user_metadata.username||user.user_metadata.name))||(user&&user.email?user.email.split("@")[0]:"Player")}
function inventory(){var a=[];document.querySelectorAll(".inventoryItem").forEach(function(n,i){var p=n.querySelector(".itemPrice"),img=n.querySelector("img"),v=Number(String(p?p.textContent:"").replace(/[^0-9.-]/g,""))||0;a.push({id:n.id||("item-"+i),price:v,image:img?img.src:"",label:n.getAttribute("data-name")||n.title||"Skin"})});return a.slice(0,500)}
async function snapshot(){if(!client||!user)return;var w=Number(String(el("money")?el("money").textContent:"0").replace(/[^0-9.-]/g,""))||0;var r=await client.from("caseclicker_player_snapshots").upsert({user_id:user.id,username:username(),wallet:w,inventory:inventory(),updated_at:new Date().toISOString()});if(r.error)console.warn(r.error.message)}
async function authUI(){var a=el("ccSocialAuth"),p=el("ccSocialApp"),s=el("ccSocialSigned");if(!a||!p||!s)return;s.textContent=user?"ONLINE: "+username():"OFFLINE";a.style.display=user?"none":"block";p.style.display=user?"block":"none"}
async function signin(){var r=await client.auth.signInWithPassword({email:el("ccEmail").value.trim(),password:el("ccPassword").value});if(r.error)throw r.error;user=r.data.user;await authUI();await snapshot();await loadParty();await jackpots();status("Signed in as "+username())}
async function signup(){var e=el("ccEmail").value.trim(),r=await client.auth.signUp({email:e,password:el("ccPassword").value,options:{data:{username:e.split("@")[0]}}});if(r.error)throw r.error;if(r.data.session){user=r.data.user;await authUI();await snapshot();status("Account created and signed in.")}else status("Account created. Check your email if confirmation is enabled.")}
async function signout(){await client.auth.signOut();user=null;party=null;members=[];selectedItems.clear();await authUI();renderParty();jackpotsRender([]);status("Signed out.")}
async function requireSession(){if(!client)throw new Error("Social service is still loading.");var s=await client.auth.getSession();if(s.error)throw s.error;if(!s.data||!s.data.session){user=null;await authUI();throw new Error("Sign in to CaseClicker Social before creating or joining a party.");}user=s.data.session.user;return s.data.session}
async function createParty(){await requireSession();var name=(el("ccPartyName").value||"CaseClicker Party").trim().slice(0,40)||"CaseClicker Party";var max=Math.max(2,Math.min(8,Number(el("ccPartyMax").value)||8));var r=await client.rpc("create_caseclicker_party",{p_name:name,p_max_members:max});if(r.error)throw r.error;var created=Array.isArray(r.data)?r.data[0]:r.data;if(!created||!created.id)throw new Error("Party creation returned no party. Please sign in again and retry.");party=created;await loadParty();broadcast("party-changed");status("Party created. Code: "+party.code)}
async function joinParty(){await requireSession();var c=(el("ccPartyCode").value||"").trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(c))return status("Enter a valid 6-character party code.",true);var r=await client.rpc("join_caseclicker_party",{p_code:c});if(r.error)throw r.error;var joined=Array.isArray(r.data)?r.data[0]:r.data;if(!joined||!joined.id)throw new Error("Party join returned no party. Please sign in again and retry.");party=joined;await loadParty();broadcast("party-changed");status("Joined party "+party.code+".")}
async function leaveParty(){if(!party)return;var r=await client.rpc("leave_caseclicker_party",{p_party_id:party.id});if(r.error)throw r.error;party=null;members=[];await loadParty();broadcast("party-changed");status("Left party.")}
async function loadParty(){if(!client||!user)return;var m=await client.from("caseclicker_party_members").select("party_id,user_id,joined_at").eq("user_id",user.id).order("joined_at",{ascending:false}).limit(1);if(m.error)return status(m.error.message,true);if(!m.data||!m.data.length){party=null;members=[];renderParty();return}var p=await client.from("caseclicker_parties").select("*").eq("id",m.data[0].party_id).maybeSingle();if(p.error)return status(p.error.message,true);party=p.data;var ms=await client.from("caseclicker_party_members").select("user_id,joined_at").eq("party_id",party.id).order("joined_at");members=ms.data||[];await partySnapshots();renderParty()}
async function partySnapshots(){if(!party||!members.length)return;var ids=members.map(function(m){return m.user_id}),r=await client.from("caseclicker_player_snapshots").select("user_id,username,wallet,inventory,updated_at").in("user_id",ids);if(r.error)return status(r.error.message,true);var map={};(r.data||[]).forEach(function(s){map[s.user_id]=s});members=members.map(function(m){return Object.assign({},m,{snapshot:map[m.user_id]||null})})}
function renderParty(){var b=el("ccPartyMembers"),t=el("ccPartyTitle");if(!b||!t)return;if(!party){t.textContent="NO PARTY";b.innerHTML='<div class="ccEmpty">Create a party or join one with a code.</div>';return}t.textContent=party.name+" • "+party.code;b.innerHTML=members.map(function(m){var s=m.snapshot,inv=s&&Array.isArray(s.inventory)?s.inventory:[],v=inv.reduce(function(x,i){return x+Number(i.price||0)},0);return '<button class="ccMember" data-user="'+esc(m.user_id)+'"><span>'+esc((s&&s.username)||"Player")+(m.user_id===user.id?" YOU":"")+'</span><span>'+inv.length+" skins • "+money(v)+'</span><span>'+money(s&&s.wallet)+'</span></button>'}).join("")||'<div class="ccEmpty">Party is empty.</div>';b.querySelectorAll(".ccMember").forEach(function(n){n.onclick=function(){viewInventory(n.getAttribute("data-user"))}})}
function viewInventory(id){var m=members.find(function(x){return x.user_id===id}),modal=el("ccInventoryViewer"),body=el("ccInventoryViewerBody");if(!m||!modal||!body)return;var s=m.snapshot,inv=s&&Array.isArray(s.inventory)?s.inventory:[];body.innerHTML='<div class="ccViewerHeader"><b>'+esc((s&&s.username)||"Player")+'</b><span>Wallet: '+money(s&&s.wallet)+" • "+inv.length+' skins</span></div><div class="ccInventoryGrid">'+inv.map(function(i){return '<div class="ccSkin">'+(i.image?'<img src="'+esc(i.image)+'" alt="">':'<div class="ccNoImage"></div>')+'<span>'+esc(i.label||"Skin")+'</span><b>'+money(i.price)+'</b></div>'}).join("")+"</div>";modal.classList.add("visible")}
async function createJackpot(){var r=await client.rpc("create_caseclicker_jackpot",{p_max_players:Math.max(2,Math.min(50,Number(el("ccJackpotMax").value)||20)),p_min_value:Math.max(0,Number(el("ccJackpotMin").value)||0)});if(r.error)throw r.error;await jackpots();broadcast("jackpot-changed");status("Jackpot created.")}
async function jackpots(){if(!client||!user)return;var r=await client.from("caseclicker_jackpots").select("*").eq("status","open").gt("closes_at",new Date().toISOString()).order("created_at",{ascending:false}).limit(20);if(r.error)return status(r.error.message,true);jackpotsRender(r.data||[])}
function jackpotsRender(list){var b=el("ccJackpots");if(!b)return;b.innerHTML=list.map(function(j){return '<div class="ccJackpot"><div><b>'+esc(j.code)+'</b><span>'+esc(j.status)+'</span></div><div>Total: '+money(j.total_value)+" • Max players: "+j.max_players+'</div><button data-jp="'+j.id+'">JOIN WITH SELECTED SKINS</button></div>'}).join("")||'<div class="ccEmpty">No open jackpots.</div>';b.querySelectorAll("[data-jp]").forEach(function(n){n.onclick=function(){joinJackpot(n.getAttribute("data-jp"))}})}
async function joinJackpot(id){var r=await client.from("caseclicker_jackpots").select("*").eq("id",id).single();if(r.error)throw r.error;var chosen=inventory().filter(function(i){return selectedItems.has(i.id)}).slice(0,7),value=chosen.reduce(function(x,i){return x+Number(i.price||0)},0);if(!chosen.length)return status("Select up to 7 skins first.",true);var j=await client.rpc("join_caseclicker_jackpot",{p_jackpot_id:id,p_items:chosen,p_value:value});if(j.error)return status(j.error.message,true);selectedItems.clear();await jackpots();broadcast("jackpot-changed");status("Joined jackpot with "+chosen.length+" skins worth "+money(value)+".")}
function selectable(){var b=el("ccSelectableInventory");if(!b)return;var inv=inventory();b.innerHTML=inv.slice(0,80).map(function(i){return '<label class="ccSelectSkin"><input type="checkbox" data-skin="'+esc(i.id)+'"'+(selectedItems.has(i.id)?" checked":"")+"><span>"+esc(i.label||"Skin")+"</span><b>"+money(i.price)+"</b></label>"}).join("")||'<div class="ccEmpty">Your inventory is empty.</div>';b.querySelectorAll("input").forEach(function(n){n.onchange=function(){if(this.checked&&selectedItems.size>=7){this.checked=false;return status("A jackpot entry can contain at most 7 skins.",true)}if(this.checked)selectedItems.set(this.getAttribute("data-skin"),true);else selectedItems.delete(this.getAttribute("data-skin"));selectedTotal()}});selectedTotal()}
function selectedTotal(){var t=0,c=0;inventory().forEach(function(i){if(selectedItems.has(i.id)){t+=Number(i.price||0);c++}});var n=el("ccSelectedTotal");if(n)n.textContent=c+"/7 selected • "+money(t)}
function broadcast(e){if(channel)channel.send({type:"broadcast",event:e,payload:{at:Date.now()}})}
function realtime(){channel=client.channel("caseclicker-social").on("broadcast",{event:"party-changed"},function(){if(user)loadParty()}).on("broadcast",{event:"jackpot-changed"},function(){if(user)jackpots()}).subscribe();presenceChannel=client.channel("caseclicker-party-presence").on("presence",{event:"sync"},function(){var state=presenceChannel.presenceState(),online=new Set;Object.keys(state).forEach(function(k){(state[k]||[]).forEach(function(p){if(p.user_id)online.add(p.user_id)})});document.querySelectorAll(".ccMember").forEach(function(n){n.classList.toggle("online",online.has(n.getAttribute("data-user")))})}).subscribe(function(s){if(s==="SUBSCRIBED"&&user)presenceChannel.track({user_id:user.id,username:username()})})}
function build(){if(el("caseClickerSocial"))return;var p=document.createElement("section");p.id="caseClickerSocial";p.className="ccSocialPanel";p.innerHTML='<div class="ccSocialHeader"><div><b>CASECLICKER SOCIAL</b><span id="ccSocialSigned">OFFLINE</span></div><button id="ccSocialClose">×</button></div><div id="ccSocialAuth"><div class="ccSection"><h3>ACCOUNT</h3><input id="ccEmail" type="email" placeholder="Email"><input id="ccPassword" type="password" placeholder="Password"><div class="ccButtons"><button id="ccSignIn">SIGN IN</button><button id="ccSignUp">CREATE ACCOUNT</button></div></div></div><div id="ccSocialApp"><div class="ccSection"><h3>PARTY</h3><div class="ccPartyControls"><input id="ccPartyName" placeholder="Party name" value="CaseClicker Party"><input id="ccPartyMax" type="number" min="2" max="8" value="8"><button id="ccCreateParty">CREATE</button></div><div class="ccPartyControls"><input id="ccPartyCode" maxlength="6" placeholder="6-character code"><button id="ccJoinParty">JOIN</button><button id="ccLeaveParty">LEAVE</button></div><h4 id="ccPartyTitle">NO PARTY</h4><div id="ccPartyMembers"></div></div><div class="ccSection"><h3>JACKPOTS</h3><div class="ccPartyControls"><input id="ccJackpotMax" type="number" min="2" max="50" value="20"><input id="ccJackpotMin" type="number" min="0" step="0.01" value="0"><button id="ccCreateJackpot">CREATE JACKPOT</button></div><div id="ccSelectableInventory"></div><div id="ccSelectedTotal">0/7 selected • $0.00</div><div id="ccJackpots"></div></div><div class="ccSection"><button id="ccSignOut">SIGN OUT</button></div></div><div id="ccSocialStatus" class="ccSocialStatus">Connect to CaseClicker Social.</div>';document.body.appendChild(p);var v=document.createElement("section");v.id="ccInventoryViewer";v.className="ccInventoryViewer";v.innerHTML='<div class="ccViewerBox"><button id="ccViewerClose">×</button><div id="ccInventoryViewerBody"></div></div>';document.body.appendChild(v);el("ccSocialClose").onclick=function(){p.classList.remove("visible")};el("ccViewerClose").onclick=function(){v.classList.remove("visible")};el("ccSignIn").onclick=function(){signin().catch(function(e){status(e.message||String(e),true)})};el("ccSignUp").onclick=function(){signup().catch(function(e){status(e.message||String(e),true)})};el("ccSignOut").onclick=function(){signout().catch(function(e){status(e.message||String(e),true)})};el("ccCreateParty").onclick=async function(){var b=this;b.disabled=true;status("Creating party...");try{await createParty()}catch(e){status(e.message||String(e),true)}finally{b.disabled=false}};el("ccJoinParty").onclick=async function(){var b=this;b.disabled=true;status("Joining party...");try{await joinParty()}catch(e){status(e.message||String(e),true)}finally{b.disabled=false}};el("ccLeaveParty").onclick=function(){leaveParty().catch(function(e){status(e.message||String(e),true)})};el("ccCreateJackpot").onclick=function(){createJackpot().catch(function(e){status(e.message||String(e),true)})}}
function open(){var p=el("caseClickerSocial");if(p){p.classList.add("visible");selectable();if(user){snapshot();loadParty();jackpots()}}}
function button(){var n=document.querySelector(".navbar ul");if(!n||el("ccSocialButton"))return;var b=document.createElement("li");b.id="ccSocialButton";b.className="ccSocialButton";b.textContent="SOCIAL";b.onclick=open;n.appendChild(b)}
async function init(){build();button();if(!window.supabase||!window.supabase.createClient)return status("Supabase client failed to load.",true);client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});client.auth.onAuthStateChange(function(e,s){user=s?s.user:null;authUI();if(user)setTimeout(function(){snapshot();loadParty();jackpots();if(presenceChannel)presenceChannel.track({user_id:user.id,username:username()})},0)});realtime();var s=await client.auth.getSession();user=s.data&&s.data.session?s.data.session.user:null;await authUI();if(user){await snapshot();await loadParty();await jackpots()}setInterval(function(){if(user){snapshot();if(el("caseClickerSocial")&&el("caseClickerSocial").classList.contains("visible"))selectable()}},10000)}
window.caseClickerSocial={open:open,getUser:function(){return user},getParty:function(){return party}};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();